#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math
from dnslib import DNSRecord, DNSHeader, RR, QTYPE, A

class Server:
    def __init__(self, root_ip, domain, port):
        self.root_ip = root_ip
        self.domain = domain.split("/")[1].removesuffix(".zone")
        self.zone_path = domain

        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(("0.0.0.0", port))
        self.port = self.socket.getsockname()[1]

        self.log("Bound to port %d" % self.port)

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def send(self, addr, message):
        self.log("Sending message:\n%s" % message)
        self.socket.sendto(message.pack(), addr)

    def recv(self, socket):
        data, addr = socket.recvfrom(65535)
        incoming_ip, incoming_port = addr
        print("addr", addr)

        # Unpack the DNS request
        request = DNSRecord.parse(data)
        #self.log("Received message:\n%s" % request)
        self.log("Received message")
        print(request)

        # YOU WILL NEED TO ACTUALLY DO SOMETHING SMART HERE
        # WE ARE JUST REPLYING WITH A FIXED RESPONSE
        response = request.reply()
        response.add_answer(RR("abc.com", QTYPE.A, rdata=A("1.2.3.4"), ttl=60))       
        
        self.send(addr, response)
    
    #given a request header we determine the correct response back to client
    def determine_response(self, request, incoming_ip):
        #If request is for domain we are authoritative over, return the correct response
        #If request is for a domain we are not authoritative over, then determine if client is local, if is then forward request to root server, else reject
        qname = str(request.q.qname)
        is_authoritative = qname.endswith(self.domain_name) or qname.endswith("." + self.domain_name)
        is_local = incoming_ip == "127.0.0.1"
        response = request.reply()
        if is_authoritative:
            # Return the correct response for the authoritative domain
            response.header.aa = 1
            response.add_answer
            pass
        elif is_local:
            # Forward the request to the root server and return the response
            pass
        else:
            # Reject the request
            pass

    def run(self):
        seq = 0
        print(self.domain)
        print(self.domain_name)
        print(self.port)
        print(self.root_ip)
        while True:
            socks = select.select([self.socket], [], [], 0.1)[0]
            for conn in socks:
                self.recv(conn)

        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='send data')
    parser.add_argument('root_ip', type=str, help="The IP address of the root server")
    parser.add_argument('zone', type=str, help="The zone file for this server")
    parser.add_argument('--port', type=int, help="The port this server should bind to", default=0)
    args = parser.parse_args()
    sender = Server(args.root_ip, args.zone, args.port)
    sender.run()
