#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math
from enum import Enum
from dnslib import DNSRecord, DNSHeader, RR, QTYPE, A, DNSQuestion


class RecordType(Enum):
    """DNS Record Type Numbers"""
    A = 1
    NS = 2
    CNAME = 5
    SOA = 6
    MX = 15
    TXT = 16

class Server:
    def __init__(self, root_ip, domain, port):
        self.root_ip = root_ip
        self.domain = domain.split("/")[1].removesuffix(".zone") + "."
        self.zone_path = domain
        self.temp_sockets = []
        self.socket_to_port_tracker = dict() #Map temporary socket objects directly to their client ports

        with open(self.zone_path, "r") as f:
                zone_text = f.read()
                print(zone_text)
        recordList = list(RR.fromZone(zone_text))
        self.recordList = recordList
        self.records = dict()
        values = [r.value for r in RecordType]
        for value in values:
            self.records[value] = []
        for record in recordList:
            self.records[record.rtype].append(record)
        

        

        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(("0.0.0.0", port))
        self.port = self.socket.getsockname()[1]

        self.log("Bound to port %d" % self.port)

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def send(self, addr, message,target_socket):
        self.log("Sending message:\n%s" % message)
        #self.socket.sendto(message.pack(), addr)
        target_socket.sendto(message.pack(),addr)

    def recv(self, socket):
        data, addr = socket.recvfrom(65535)
        incoming_ip, incoming_port = addr
        print("INCOMING PORT:", incoming_port)

        # Unpack the DNS request
        request = DNSRecord.parse(data)
        #self.log("Received message:\n%s" % request)
        self.log("Received message")
        print(request)

        
        response = self.determine_response(request, incoming_ip, incoming_port)
        if response == None:
            pass
        #response.add_answer(RR("abc.com", QTYPE.A, rdata=A("1.2.3.4"), ttl=60))       
        else:
            self.send(addr, response, self.socket)

    #returns a mini dictionary of records
    def find_records(self,domain_name):
        found_records = []
        for record in self.recordList:
            if record.rname == domain_name:
                found_records.append(record)
        return found_records
    
    #Recursively goes through zone file CNAME records to find the correct A record if one exists, otherwise returns the CNAME record
    #Returns record object
    #no defense against zone file CNAMe loops
    #
    def recursive_cname_query(self,response, current_CNAME_record,glue=False):
        if current_CNAME_record.rtype == RecordType.CNAME.value:
            if glue == False:
                response.add_answer(current_CNAME_record)
            next_record = self.find_records(current_CNAME_record.rdata.label)
            if len(next_record) == 1 and next_record[0].rtype == RecordType.CNAME.value: #The next chained record is a CNAME record
                return self.recursive_cname_query(response, next_record[0],glue)
            else: #The next chained record is actually A records
                for record in next_record:
                    if glue == False:
                        response.add_answer(record)
                    elif glue == True:
                        response.add_ar(record)
        elif current_CNAME_record.rtype == RecordType.A.value: #we have reached the end of the CNAMe chain and arrived at an A record
            if glue == False:
                response.add_answer(current_CNAME_record)
            elif glue == True:
                response.add_ar(current_CNAME_record)
        return response

    #given a request header we construct the correst response object and return it
    def determine_response(self, request, incoming_ip,incoming_port):
        #print("INCOMING IP:",incoming_ip)
        #If request is for domain we are authoritative over, return the correct response
        #If request is for a domain we are not authoritative over, then determine if client is local, if is then forward request to root server, else reject
        qname = request.q.qname
        qtype = request.q.qtype
        is_authoritative = str(qname).endswith(self.domain) or str(qname).endswith("." + self.domain)
        is_local = (incoming_ip == "127.0.0.1")
        response = request.reply()
        
        if is_authoritative:
            #do this only if this dns server is authoritative for the req domain
            response.header.aa = 1
            
            relevant_NS_records = [record for record in self.records[RecordType.NS.value] if record.rname == qname]
            relevant_A_records = [record for record in self.records[RecordType.A.value] if record.rname == qname]
            relevant_CNAME_records = [record for record in self.records[RecordType.CNAME.value] if record.rname == qname]
            relevant_MX_records = [record for record in self.records[RecordType.MX.value] if record.rname == qname]
            relevant_TXT_records = [record for record in self.records[RecordType.TXT.value] if record.rname == qname]

            if qtype == RecordType.NS.value:

                for NS_record in relevant_NS_records:
                    response.add_auth(NS_record)
                for A_record in relevant_A_records:#This only scans for any A records with the same name as the requested NS record. Not usable for any A records that those uncovered NS records point to
                    response.add_ar(A_record)
                for NS_record in relevant_NS_records:
                    subrelevant_A_records = [record for record in self.records[RecordType.A.value] if record.rname == NS_record.rdata.label]
                    for A_record in subrelevant_A_records:
                        response.add_ar(A_record)
                #add CNAME resolving search
                for CNAME_record in relevant_CNAME_records:
                    response = self.recursive_cname_query(response,CNAME_record,True)
            elif qtype == RecordType.A.value:
                if len(relevant_NS_records) > 0: #If there are relevant NS records for this A record query
                    for NS_record in relevant_NS_records:
                        response.add_auth(NS_record)
                    for A_record in relevant_A_records:
                        response.add_ar(A_record)
                    #Add CNAMe record search but with glue
                    for CNAME_record in relevant_CNAME_records:
                        response = self.recursive_cname_query(response,CNAME_record,True)
                else: #If there are no relevant NS records for this A record query
                    if len(relevant_A_records) > 0: #If there are relevant A records for this A record query
                        for A_record in relevant_A_records:
                            response.add_answer(A_record)
                        #add own NS records, NOT relevant NS records, it is optional but prolly do it later
                    #Also search for CNAMe record search
                    elif len(relevant_CNAME_records) > 0:
                        for CNAME_record in relevant_CNAME_records:
                            response = self.recursive_cname_query(response,CNAME_record,False)
                    else:#We have found no relevant NS record or A records for this A record query
                        response.header.rcode = 3 #NXDOMAIN No A records exist for the domain, but we are authoritative so we return NXDOMAIN
            elif qtype == RecordType.MX.value:
                for MX_record in relevant_MX_records:
                    response.add_answer(MX_record)
            elif qtype == RecordType.TXT.value:
                for TXT_record in relevant_TXT_records:
                    response.add_answer(TXT_record)
        elif is_local:
            self.handle_dns_lookup(request,(incoming_ip,incoming_port))
            #forward the request to the root server and return the response
            response = None
            pass
        else:
            response.header.rcode = 5 #REFUSED
            pass
        return response
    
    #This function STARTS the action to create a temp socket for a specific portion of the requested domain name and add it to the temp socket list
    #Does not return anything by itself
    #
    def handle_dns_lookup(self,request,client_addr): #This only runs once per request
        temp_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        client_q = request.questions[0]
        question_dns_record = DNSRecord(q=DNSQuestion(client_q.qname, client_q.qtype)) #Not all requests will be for A records, add more to this so it can also request for NS records.
        self.socket_to_port_tracker[temp_socket] = {
            "client_ip": client_addr[0],
            "client_port":client_addr[1],
            "request_object":request,
            "ns_list":[self.root_ip], #root server is the first NS we need to get the train started with
            "ns_index":0
        }
        self.send_request((self.root_ip,60053),question_dns_record,temp_socket) #This sends the actual request to the root server and appends to temp_socket list
    
    #addr_tuple should usually be (self.root_ip,60053)
    #Sends the actual request and appends the temp socket to the socket list
    def send_request(self,addr_tuple,dns_record,target_socket): #This only runs once per request
        self.send(addr_tuple,dns_record,target_socket)#This gets the actual NS chain train rolling
        self.temp_sockets.append(target_socket) 
    
    #This function should be called a lot in the run() function to constantly check the temp socket list to see if any of the sockets have reponses
    #if they do, try to resolve them to their immediate NS or A records.
    #If they are A records, figure out how to send them to our client through self.socket
    #If they are NS records, call handle dns lookup and append into temp socket list to resolve the NEXT step of the domain name.
    def process_socket_response(self,temp_socket):
        data, addr = temp_socket.recvfrom(65535)

        # Unpack the DNS response
        response = DNSRecord.parse(data)
        answer_section = response.rr
        authority_section = response.auth
        additional_section = response.ar

        if len(answer_section) > 0: #Has immediate ip addr! Check it and send it back to the client.
            response.header.aa = 0
            response.header.ra = 1
            response.header.id = self.socket_to_port_tracker[temp_socket]["request_object"].header.id #copy the original id over
            client_ip = self.socket_to_port_tracker[temp_socket]["client_ip"]
            client_port = self.socket_to_port_tracker[temp_socket]["client_port"]
            client_addr = (client_ip,client_port)
            self.send(client_addr,response,self.socket)
        elif len(authority_section) > 0: #Has nearby NS server instead, check it out, send request to that NS server, then reappend this back into the temp socket list
            #this is where we will also want to check out additional_section
            ns_list = self.socket_to_port_tracker[temp_socket]["ns_list"]
            ns_index = self.socket_to_port_tracker[temp_socket]["ns_index"]
            


            authority_ns_list = []
            for record in authority_section:
                if record.rtype == RecordType.NS.value:
                    authority_ns_list.append(str(record.rdata).strip("."))
            for record in additional_section:
                rname_str = str(record.rname).strip(".")
                if rname_str in authority_ns_list and record.rtype == RecordType.A.value:
                    print("bailiwick is working correctly")
                    ns_list.append(str(record.rdata))

            original_request_object = self.socket_to_port_tracker[temp_socket]["request_object"]
            self.socket_to_port_tracker[temp_socket]["ns_index"] = ns_index + 1 #We just hit one of the NS servers on the ns_list! We increment the index
            self.send((ns_list[self.socket_to_port_tracker[temp_socket]["ns_index"]],60053),original_request_object,temp_socket)
            

            print("WE DONT HAVE IMMEDIATE ANSWER")
            pass
        else: #Change this to an elif statement to determine if ns_index reached end of ns_list
            pass
        

        
        #response = self.determine_response(request, incoming_ip)
        if response == None:
            pass
              
        else:
            self.send(addr, response, self.socket)

    def run(self):
        seq = 0

        while True:
            socks = select.select([self.socket] + self.temp_sockets, [], [], 0.1)[0]
            
            for conn in socks:
                if conn == self.socket:
                    self.recv(conn)
                else:
                    self.process_socket_response(conn)

        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='send data')
    parser.add_argument('root_ip', type=str, help="The IP address of the root server")
    parser.add_argument('zone', type=str, help="The zone file for this server")
    parser.add_argument('--port', type=int, help="The port this server should bind to", default=0)
    args = parser.parse_args()
    sender = Server(args.root_ip, args.zone, args.port)
    sender.run()
